import Constants from 'expo-constants'

// const SAE_EMPLOYEEAPP_API_URL = 'http://127.0.0.1:3333/api'
// // const SAE_EMPLOYEEAPP_API_URL = 'https://api-principal.bo-sae.com.mx/api'
// const SAE_EMPLOYEEAPP_AUTHENTICATION_KEY = 'AUTHENTICATION_KEY_9FD8FAFD-F6A2-4D0C-B3B4-C3FA7B99AB34'
// const SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY = 'AUTHENTICATION_USER_KEY-F6A2-4D0C-B3B4-C3FA7B99AB34'
// const SAE_EMPLOYEEAPP_THEME_STORAGE_KEY = 'THEME_STORAGE_KEY-F6A2-4D0C-B3B4-C3FA7B99AB34'

interface IEnvironment {
  SAE_EMPLOYEEAPP_API_URL: string
  SAE_EMPLOYEEAPP_AUTHENTICATION_KEY: string
  SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY: string
  SAE_EMPLOYEEAPP_THEME_STORAGE_KEY: string
}

// const developmentEnvironment: IEnvironment = {
//   SAE_EMPLOYEEAPP_API_URL: SAE_EMPLOYEEAPP_API_URL,
//   SAE_EMPLOYEEAPP_AUTHENTICATION_KEY: SAE_EMPLOYEEAPP_AUTHENTICATION_KEY,
//   SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY: SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY,
//   SAE_EMPLOYEEAPP_THEME_STORAGE_KEY: SAE_EMPLOYEEAPP_THEME_STORAGE_KEY
// }

const {
  SAE_EMPLOYEEAPP_API_URL,
  SAE_EMPLOYEEAPP_AUTHENTICATION_KEY,
  SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY,
  SAE_EMPLOYEEAPP_THEME_STORAGE_KEY
} = Constants.expoConfig?.extra as IEnvironment

const environment = {
  SAE_EMPLOYEEAPP_API_URL: SAE_EMPLOYEEAPP_API_URL || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_AUTHENTICATION_KEY: SAE_EMPLOYEEAPP_AUTHENTICATION_KEY || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY: SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_THEME_STORAGE_KEY: SAE_EMPLOYEEAPP_THEME_STORAGE_KEY || 'NOT ASSIGNED'
}

// const environment = developmentEnvironment // Constants.expoConfig?.extra?.env === 'preview' ? previewEnvironment : developmentEnvironment

export { environment }
